# Generated by Django 5.0.7 on 2024-09-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_goals', '0002_goalprogress_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_goals.goal')),
            ],
        ),
    ]
