# Generated by Django 5.1.4 on 2025-01-11 16:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_goals', '0009_goal_waiting_for_not_achieved_count'),
        ('example_app', '0002_mergesort'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartitionSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('partition_done', models.BooleanField(default=False)),
                ('low_done', models.BooleanField(default=False)),
                ('high_done', models.BooleanField(default=False)),
                ('sorted_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_goals.goal')),
                ('subsort_high', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='example_app.partitionsort')),
                ('subsort_low', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='example_app.partitionsort')),
            ],
        ),
    ]
