# Generated by Django 5.2 on 2025-04-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_goals", "0010_remove_goal_goals_waiting_for_failed_idx_and_more"),
        ("example_app", "0003_partitionsort"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorsBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired", models.PositiveIntegerField(default=10)),
                ("spawned", models.PositiveIntegerField(default=0)),
                ("succeeded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                (
                    "processed_goal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_goals.goal",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
