# Generated by Django 5.2.9 on 2025-12-17 00:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example_app", "0004_errorsbatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partitionsort",
            name="sorted_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
