# GitHub Copilot Environment Configuration
# Configures the development environment for django-goals

setup:
  name: Django Goals Development Environment
  
  # Use composite action that sets up complete environment
  action: ./.github/actions/setup-django-goals
  
  # PostgreSQL service for database functionality
  services:
    postgres:
      image: postgres:16
      env:
        POSTGRES_PASSWORD: postgrespass
        POSTGRES_DB: django_goals
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        - 5432:5432