[cosmic-ray]
module-path = "django_goals"
timeout = 40.0
excluded-modules = [
    "**/migrations/**",
    "**/*_tests.py",
    "**/conftest.py",
    "django_goals/factories.py",
]
test-command = "pytest"

[cosmic-ray.distributor]
name = "http"

[cosmic-ray.distributor.http]
worker-urls = [
    "http://localhost:9876",
    "http://localhost:9877",
    "http://localhost:9878",
    "http://localhost:9879",
    "http://localhost:9880",
    "http://localhost:9881",
    "http://localhost:9882",
    "http://localhost:9883",
]
