# Generated by Django 5.0.6 on 2024-06-10 12:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('blocked', 'Blocked'), ('waiting_for_date', 'Waiting For Date'), ('waiting_for_preconditions', 'Waiting For Preconditions'), ('waiting_for_worker', 'Waiting For Worker'), ('done', 'Done'), ('given_up', 'Given Up'), ('corrupted', 'Corrupted'), ('not_going_to_happen_soon', 'Not Going To Happen Soon')], db_index=True, default='waiting_for_date', max_length=30)),
                ('task_type', models.CharField(max_length=100)),
                ('instructions', models.JSONField(null=True)),
                ('precondition_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Task will not be executed before this date. Also used as priority for tasks that are waiting for worker - tasks with earlier date will be preferred.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='django_goals.task')),
                ('precondition_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='django_goals.task')),
            ],
            options={
                'unique_together': {('dependent_task', 'precondition_task')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='precondition_tasks',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', through='django_goals.TaskDependency', to='django_goals.task'),
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_taken', models.DurationField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='django_goals.task')),
            ],
            options={
                'ordering': ('task', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('state', 'waiting_for_date')), fields=['precondition_date'], name='tasks_waiting_for_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('state', 'waiting_for_worker')), fields=['precondition_date'], name='tasks_waiting_for_worker_idx'),
        ),
    ]
