# Generated by Django 6.1.2 on 2026-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_goals", "0011_goalpickup"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="deadline_propagated",
            field=models.BooleanField(
                default=True,
                help_text="Whether the deadline got to dependencies of this goal.",
            ),
        ),
        migrations.AddField(
            model_name="goaldependency",
            name="deadline_propagated",
            field=models.BooleanField(
                default=True,
                help_text="Whether the deadline of the dependent goal got to the precondition goal.",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                condition=models.Q(("deadline_propagated", False)),
                fields=["deadline"],
                name="goals_deadline_propagation_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goaldependency",
            index=models.Index(
                condition=models.Q(("deadline_propagated", False)),
                fields=["id"],
                name="goals_dependency_deadline_idx",
            ),
        ),
    ]
