name: Test Django Goals Composite Action

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/copilot-setup-steps.yml'
      - '.github/actions/setup-django-goals/**'

jobs:
  test-copilot-setup:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgrespass
          POSTGRES_DB: django_goals
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Django Goals Environment
        uses: ./.github/actions/setup-django-goals
        
      - name: Test Django Goals functionality
        run: |
          echo "Testing Django Goals commands..."
          poetry run python manage.py help | grep goals_
          
          echo "Testing model creation..."
          poetry run python manage.py shell -c "
          from django_goals.models import Goal, GoalState
          from django.contrib.auth.models import User
          
          # Test basic model functionality
          print('Models imported successfully')
          print('Goal states:', [s for s, _ in GoalState.choices])
          "
          
          echo "✅ Django Goals environment test completed successfully"